version: "3.2"

services:
  # app:
  #   build: .
  #   container_name: mtg-trading-api
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports: 
  #     - 7777:7777
  #   links: 
  #    - postgres
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge